-- Trigger to update TICKET_PRICE_HISTORY table when the price of the air ticket is updated in TICKET2 table.
-- CREATING TABLE TICKET_PRICE_HISTORY--
CREATE TABLE TICKET_PRICE_HISTORY
(DATE_OF_BOOKING DATE NOT NULL,
SOURCE VARCHAR(3) NOT NULL,
DESTINATION VARCHAR(3) NOT NULL,
CLASS VARCHAR2(15) NOT NULL,
PRICE INT,
PRIMARY KEY(DATE_OF_BOOKING, SOURCE, DESTINATION, CLASS));
-- CREATE A TRIGGER TICKET_PRICE_HISTORY --
CREATE OR REPLACE TRIGGER TRIGG_TICKET_PRICE_HISTORY
BEFORE UPDATE OF PRICE
ON TICKET2
FOR EACH ROW
BEGIN
INSERT INTO TICKET_PRICE_HISTORY
VALUES(:OLD.DATE_OF_BOOKING, :OLD.SOURCE, :OLD.DESTINATION, :OLD.CLASS, :OLD.PRICE);
END;
--LET'S UPDATE A PRICE OR FARE OF AN AIR TICKET --
UPDATE TICKET2
SET PRICE=150000
WHERE DATE_OF_BOOKING ='11-NOV-16'
AND SOURCE='BOM'
AND DESTINATION='DFW'
AND CLASS='ECONOMY'
