CREATE OR REPLACE TRIGGER DELAYEDFLIGHTS
AFTER INSERT ON FLIGHT
FOR EACH ROW
BEGIN
IF UPDATING('STATUS')
THEN
INSERT INTO DELAYED_FLIGHTS (FLIGHT_CODE, SOURCE, DESTINATION , AIRLINEID ,REPORT_TIME)
VALUES(:NEW.FLIGHT_CODE,:NEW.SOURCE,:NEW.DESTINATION,:NEW.AIRLINEID,sysdate);
END IF;
END;    
-- This is audit table for this trigger--
CREATE TABLE DELAYED_FLIGHTS
(FLIGHT_CODE VARCHAR2(20),
DESTINATION VARCHAR2(20),
SOURCE VARCHAR2(20),
AIRLINEID VARCHAR2(20),
REPORT_TIME DATE);
INSERT INTO FLIGHT(FLIGHT_CODE, SOURCE, DESTINATION, ARRIVAL, DEPARTURE, STATUS, DURATION,
FLIGHTTYPE, LAYOVER_TIME, NO_OF_STOPS, AIRLINEID)
VALUES('QR129','BOM','DFW','02:10','03:15','Delayed','24hr','Connecting',3,1,'AI');